import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: posts } = api.post.getAll.useQuery();

  console.log(posts); // DEBUG

  const { isLoaded, isSignedIn, user } = useUser();
  const noUserData = !isLoaded || !isSignedIn;

  return (
    <>
      <Head>
        <title>Shampoodle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-4xl font-bold text-white">
          Hello, {noUserData ? "Stranger" : user?.firstName}
        </h1>

        <div>
          {noUserData ? (
            <SignInButton mode="modal">
              <button className="bg-red-400 p-4">Sign In</button>
            </SignInButton>
          ) : (
            <SignOutButton>
              <button className="bg-red-400 p-4">Sign Out</button>
            </SignOutButton>
          )}
        </div>

        <div>
          {posts?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>

        <button className="btn-error btn">Error</button>
      </main>
    </>
  );
};

export default Home;
