import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { isLoaded, isSignedIn, user } = useUser();
  const noUserData = !isLoaded || !isSignedIn;

  return (
    <>
      <Head>
        <title>Shampoodle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1 className="text-4xl font-bold text-white">
          Hello, {noUserData ? "Stranger" : user?.firstName}
        </h1>

        {noUserData ? (
          <SignInButton mode="modal">
            <button className="bg-red-400 p-4">Sign In</button>
          </SignInButton>
        ) : (
          <SignOutButton>
            <button className="bg-red-400 p-4">Sign Out</button>
          </SignOutButton>
        )}
      </main>
    </>
  );
};

export default Home;
